#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
if [ -x "${REPO_ROOT}/.visualizer/emit-event.sh" ]; then
  _VIZ_PAYLOAD=$(jq -nc --arg agent "${AGENT_NAME:-unknown}" --arg message "${AGENT_MESSAGE:-${MESSAGE:-${SUMMARY:-}}}" '{"agentName":$agent,"agentDisplayName":$agent,"message":$message,"summary":$message}' 2>/dev/null || echo '{}')
  "${REPO_ROOT}/.visualizer/emit-event.sh" subagentStart "${_VIZ_PAYLOAD}" "${SESSION_ID:-run-$$}" >&2 || true
fi

exit 0
